### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [mmiller42/autonym-postgres-store#1]
for services like this it is a good idea to allow initialization from the pg-promise `db` object to be reused, as opposed to using explicit package reference to pg-promise ;)

at least it is good to support it as an option ;) that way other libraries can use their own version of pg-promise, and without creating multiple `db` objects for the same connection, which in development environment will create a warning:

```
WARNING: Creating a duplicate database object for the same connection.
```

**Comment by vitaly-t** [comment]
**UPDATE**

I just finished writing this documents: [Integration](https://github.com/vitaly-t/pg-promise/wiki/Integration), which is a must read when integrating with `pg-promise` ;)

**Comment by mmiller42** [comment]
@vitaly-t Hey I really wanted to thank you for providing all this feedback! It's all very helpful. I just discovered your library the other day (getting tired of callback hell) and obviously this package is a long way from being production-ready -- I was just working on a new app and was trying to break apart some of the components into independent projects.

I really appreciate your advice and will work on integrating it into this project soon!
